import type { Material, ProgressEntry, Worker } from "../ProjectDataContext";

function printWindow(htmlContent: string, title: string) {
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; font-size: 12px; color: #222; padding: 20px; }
    .header { background: #1e3a5f; color: white; padding: 16px 20px; border-radius: 6px; margin-bottom: 20px; }
    .header h1 { font-size: 18px; font-weight: bold; }
    .header h2 { font-size: 13px; opacity: 0.85; margin-top: 3px; }
    .header p { font-size: 11px; opacity: 0.7; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th { background: #1e3a5f; color: white; padding: 8px 10px; text-align: left; font-size: 11px; }
    td { padding: 7px 10px; border-bottom: 1px solid #e5e7eb; font-size: 11px; }
    tr:nth-child(even) td { background: #f9fafb; }
    .footer { margin-top: 20px; text-align: center; font-size: 10px; color: #64748b; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
    .badge-ok { background: #dcfce7; color: #16a34a; }
    .badge-low { background: #fef9c3; color: #b45309; }
    .badge-critical { background: #fee2e2; color: #dc2626; }
    @media print { body { padding: 0; } .no-print { display: none; } }
  </style>
</head>
<body>
${htmlContent}
<div class="footer">Generated by ConstructManager Pro · ${new Date().toLocaleString()} · Open Source MIT</div>
<script>window.onload = function() { window.print(); }</script>
</body>
</html>`);
  win.document.close();
}

export function exportAttendancePDF(
  workers: Worker[],
  attendance: { workerId: string; date: string; present: boolean }[],
  projectName: string,
) {
  const totalCost = workers.reduce((s, w) => {
    const days = attendance.filter(
      (a) => a.workerId === w.id && a.present,
    ).length;
    return s + days * w.dailyWageRate;
  }, 0);

  const rows = workers
    .map((w) => {
      const days = attendance.filter(
        (a) => a.workerId === w.id && a.present,
      ).length;
      return `<tr>
      <td>${w.name}</td>
      <td>${w.skill}</td>
      <td>${days}</td>
      <td>₹${w.dailyWageRate}</td>
      <td><strong>₹${days * w.dailyWageRate}</strong></td>
      <td><span class="badge ${w.status === "Active" ? "badge-ok" : ""}">${
        w.status
      }</span></td>
    </tr>`;
    })
    .join("");

  const html = `
    <div class="header">
      <h1>🏗️ ConstructManager Pro</h1>
      <h2>${projectName} — Labour Attendance & Wages Report</h2>
      <p>Generated: ${new Date().toLocaleDateString()}</p>
    </div>
    <table>
      <thead><tr>
        <th>Worker Name</th><th>Skill</th><th>Days Present</th><th>Daily Rate</th><th>Total Wages</th><th>Status</th>
      </tr></thead>
      <tbody>${rows}</tbody>
      <tfoot><tr>
        <td colspan="4" style="text-align:right;font-weight:bold;padding:8px">Grand Total:</td>
        <td style="font-weight:bold;color:#1e3a5f">₹${totalCost.toLocaleString()}</td>
        <td></td>
      </tr></tfoot>
    </table>`;

  printWindow(html, `Attendance Report – ${projectName}`);
}

export function exportMaterialsPDF(materials: Material[], projectName: string) {
  const rows = [...materials]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((m) => {
      const status =
        m.currentStock <= m.reorderLevel * 0.5
          ? "Critical"
          : m.currentStock <= m.reorderLevel
            ? "Low"
            : "OK";
      const badgeCls =
        status === "OK"
          ? "badge-ok"
          : status === "Low"
            ? "badge-low"
            : "badge-critical";
      return `<tr>
      <td>${m.name}</td>
      <td>${m.unit}</td>
      <td><strong>${m.currentStock}</strong></td>
      <td>${m.reorderLevel}</td>
      <td>₹${m.unitPrice}</td>
      <td>₹${(m.currentStock * m.unitPrice).toLocaleString()}</td>
      <td>${m.supplier}</td>
      <td><span class="badge ${badgeCls}">${status}</span></td>
    </tr>`;
    })
    .join("");

  const totalValue = materials.reduce(
    (s, m) => s + m.currentStock * m.unitPrice,
    0,
  );

  const html = `
    <div class="header">
      <h1>🏗️ ConstructManager Pro</h1>
      <h2>${projectName} — Materials Inventory Report (A–Z)</h2>
      <p>Generated: ${new Date().toLocaleDateString()} · ${materials.length} materials</p>
    </div>
    <table>
      <thead><tr>
        <th>Name (A–Z)</th><th>Unit</th><th>Stock</th><th>Reorder</th><th>Unit Price</th><th>Total Value</th><th>Supplier</th><th>Status</th>
      </tr></thead>
      <tbody>${rows}</tbody>
      <tfoot><tr>
        <td colspan="5" style="text-align:right;font-weight:bold;padding:8px">Total Inventory Value:</td>
        <td style="font-weight:bold;color:#1e3a5f">₹${totalValue.toLocaleString()}</td>
        <td colspan="2"></td>
      </tr></tfoot>
    </table>`;

  printWindow(html, `Materials Report – ${projectName}`);
}

export function exportProgressPDF(
  progressHistory: ProgressEntry[],
  projectName: string,
  currentPercent: number,
) {
  const rows = [...progressHistory]
    .reverse()
    .map(
      (p) => `<tr>
      <td>${p.date}</td>
      <td><strong>${p.percentage}%</strong></td>
      <td>${p.notes}</td>
      <td>${p.by}</td>
    </tr>`,
    )
    .join("");

  const html = `
    <div class="header">
      <h1>🏗️ ConstructManager Pro</h1>
      <h2>${projectName} — Site Progress Report</h2>
      <p>Current Completion: ${currentPercent}% · Generated: ${new Date().toLocaleDateString()}</p>
    </div>
    <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:6px;padding:12px 16px;margin-bottom:16px">
      <strong>Overall Progress:</strong>
      <div style="background:#e2e8f0;border-radius:4px;height:12px;margin-top:6px;overflow:hidden">
        <div style="background:#1e3a5f;height:100%;width:${currentPercent}%"></div>
      </div>
      <p style="margin-top:4px;font-size:11px;color:#64748b">${currentPercent}% complete</p>
    </div>
    <table>
      <thead><tr>
        <th>Date</th><th>Completion %</th><th>Notes</th><th>Updated By</th>
      </tr></thead>
      <tbody>${rows.length ? rows : "<tr><td colspan=4 style='text-align:center;color:#64748b'>No progress entries yet</td></tr>"}</tbody>
    </table>`;

  printWindow(html, `Progress Report – ${projectName}`);
}
