/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppRole = IDL.Variant({
  chiefEngineer: IDL.Null,
  siteEngineer: IDL.Null,
  materialsEngineer: IDL.Null,
  siteOwner: IDL.Null,
});

export const UserRole = IDL.Variant({
  admin: IDL.Null,
  user: IDL.Null,
  guest: IDL.Null,
});

export const Worker = IDL.Record({
  dailyWage: IDL.Nat,
  dialCode: IDL.Text,
  id: IDL.Nat,
  name: IDL.Text,
  phone: IDL.Text,
  projectId: IDL.Nat,
  skill: IDL.Text,
  wEmail: IDL.Text,
});

export const Project = IDL.Record({
  budget: IDL.Nat,
  completion: IDL.Nat,
  createdBy: IDL.Text,
  id: IDL.Nat,
  location: IDL.Text,
  name: IDL.Text,
  pwHash: IDL.Text,
  startDate: IDL.Text,
  teamCode: IDL.Text,
});

export const ProjectMember = IDL.Record({
  email: IDL.Text,
  projectId: IDL.Nat,
  role: AppRole,
});

export const ProgressEntry = IDL.Record({
  byEmail: IDL.Text,
  date: IDL.Text,
  id: IDL.Nat,
  notes: IDL.Text,
  pct: IDL.Nat,
  photos: IDL.Vec(IDL.Text),
  projectId: IDL.Nat,
});

export const PayrollRecord = IDL.Record({
  approvedBy: IDL.Text,
  id: IDL.Nat,
  period: IDL.Text,
  projectId: IDL.Nat,
  status: IDL.Text,
  submittedBy: IDL.Text,
  totalAmount: IDL.Nat,
});

export const Notification = IDL.Record({
  content: IDL.Text,
  id: IDL.Nat,
  isRead: IDL.Bool,
  nType: IDL.Text,
  timestamp: IDL.Text,
  userEmail: IDL.Text,
});

export const MaterialTx = IDL.Record({
  byEmail: IDL.Text,
  date: IDL.Text,
  id: IDL.Nat,
  materialId: IDL.Nat,
  notes: IDL.Text,
  projectId: IDL.Nat,
  qty: IDL.Nat,
  txType: IDL.Text,
});

export const Material = IDL.Record({
  id: IDL.Nat,
  name: IDL.Text,
  priceUsd: IDL.Nat,
  projectId: IDL.Nat,
  reorderLevel: IDL.Nat,
  stock: IDL.Nat,
  supplier: IDL.Text,
  unit: IDL.Text,
});

export const ChatMessage = IDL.Record({
  id: IDL.Nat,
  isDM: IDL.Bool,
  projectId: IDL.Nat,
  receiverEmail: IDL.Text,
  senderEmail: IDL.Text,
  senderName: IDL.Text,
  senderRole: IDL.Text,
  text: IDL.Text,
  timestamp: IDL.Text,
});

export const AuditEntry = IDL.Record({
  action: IDL.Text,
  area: IDL.Text,
  details: IDL.Text,
  id: IDL.Nat,
  timestamp: IDL.Text,
  userEmail: IDL.Text,
});

export const AttendanceRecord = IDL.Record({
  date: IDL.Text,
  projectId: IDL.Nat,
  status: IDL.Text,
  workerId: IDL.Nat,
});

const AddMaterialResult = IDL.Record({
  materialId: IDL.Nat,
  message: IDL.Text,
  ok: IDL.Bool,
});

const AddProgressResult = IDL.Record({
  entryId: IDL.Nat,
  message: IDL.Text,
  ok: IDL.Bool,
});

const AddWorkerResult = IDL.Record({
  message: IDL.Text,
  ok: IDL.Bool,
  workerId: IDL.Nat,
});

const OkMessage = IDL.Record({ message: IDL.Text, ok: IDL.Bool });
const OkBool = IDL.Record({ ok: IDL.Bool });

const CreateProjectResult = IDL.Record({
  message: IDL.Text,
  ok: IDL.Bool,
  projectId: IDL.Nat,
});

const JoinProjectResult = IDL.Record({
  message: IDL.Text,
  ok: IDL.Bool,
  projectId: IDL.Nat,
});

const LoginResult = IDL.Record({
  currency: IDL.Text,
  message: IDL.Text,
  name: IDL.Text,
  nationality: IDL.Text,
  ok: IDL.Bool,
  phone: IDL.Text,
  role: IDL.Text,
});

const PostChatResult = IDL.Record({ messageId: IDL.Nat, ok: IDL.Bool });

const SubmitPayrollResult = IDL.Record({
  message: IDL.Text,
  ok: IDL.Bool,
  payrollId: IDL.Nat,
});

export const idlService = IDL.Service({
  _initializeAccessControlWithSecret: IDL.Func([IDL.Text], [], []),
  addMaterial: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
    [AddMaterialResult],
    [],
  ),
  addProgress: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
    [AddProgressResult],
    [],
  ),
  addWorker: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
    [AddWorkerResult],
    [],
  ),
  approvePayroll: IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [OkMessage], []),
  assignCallerUserRole: IDL.Func([IDL.Principal, UserRole], [], []),
  changePassword: IDL.Func([IDL.Text, IDL.Text, IDL.Text], [OkMessage], []),
  createProject: IDL.Func(
    [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
    [CreateProjectResult],
    [],
  ),
  getAllProjects: IDL.Func([], [IDL.Vec(Project)], ['query']),
  getAttendance: IDL.Func([IDL.Nat], [IDL.Vec(AttendanceRecord)], ['query']),
  getAuditLog: IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
  getCallerUserRole: IDL.Func([], [UserRole], ['query']),
  getDMChat: IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  getGroupChat: IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  getMaterialTx: IDL.Func([IDL.Nat], [IDL.Vec(MaterialTx)], ['query']),
  getMaterials: IDL.Func([IDL.Nat], [IDL.Vec(Material)], ['query']),
  getNotifications: IDL.Func([IDL.Text], [IDL.Vec(Notification)], ['query']),
  getPayroll: IDL.Func([IDL.Nat], [IDL.Vec(PayrollRecord)], ['query']),
  getProgress: IDL.Func([IDL.Nat], [IDL.Vec(ProgressEntry)], ['query']),
  getProjectMembers: IDL.Func([IDL.Nat], [IDL.Vec(ProjectMember)], ['query']),
  getUserProjects: IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  getWorkers: IDL.Func([IDL.Nat], [IDL.Vec(Worker)], ['query']),
  isCallerAdmin: IDL.Func([], [IDL.Bool], ['query']),
  joinProject: IDL.Func(
    [IDL.Text, IDL.Text, IDL.Text, AppRole],
    [JoinProjectResult],
    [],
  ),
  login: IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  markAllNotifsRead: IDL.Func([IDL.Text], [OkBool], []),
  markAttendance: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
    [OkMessage],
    [],
  ),
  markNotifRead: IDL.Func([IDL.Text, IDL.Nat], [OkBool], []),
  postChat: IDL.Func(
    [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
    [PostChatResult],
    [],
  ),
  recordTx: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
    [OkMessage],
    [],
  ),
  register: IDL.Func(
    [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AppRole],
    [OkMessage],
    [],
  ),
  seedDemo: IDL.Func([], [OkBool], []),
  submitPayroll: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
    [SubmitPayrollResult],
    [],
  ),
  updateMaterial: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
    [OkMessage],
    [],
  ),
  updateProfile: IDL.Func(
    [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
    [OkMessage],
    [],
  ),
  updateTeamCode: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
    [OkMessage],
    [],
  ),
  updateWorker: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
    [OkMessage],
    [],
  ),
  verifyProjectPassword: IDL.Func(
    [IDL.Text, IDL.Nat, IDL.Text],
    [OkMessage],
    [],
  ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppRole = IDL.Variant({
    chiefEngineer: IDL.Null,
    siteEngineer: IDL.Null,
    materialsEngineer: IDL.Null,
    siteOwner: IDL.Null,
  });

  const UserRole = IDL.Variant({
    admin: IDL.Null,
    user: IDL.Null,
    guest: IDL.Null,
  });

  const Worker = IDL.Record({
    dailyWage: IDL.Nat,
    dialCode: IDL.Text,
    id: IDL.Nat,
    name: IDL.Text,
    phone: IDL.Text,
    projectId: IDL.Nat,
    skill: IDL.Text,
    wEmail: IDL.Text,
  });

  const Project = IDL.Record({
    budget: IDL.Nat,
    completion: IDL.Nat,
    createdBy: IDL.Text,
    id: IDL.Nat,
    location: IDL.Text,
    name: IDL.Text,
    pwHash: IDL.Text,
    startDate: IDL.Text,
    teamCode: IDL.Text,
  });

  const ProjectMember = IDL.Record({
    email: IDL.Text,
    projectId: IDL.Nat,
    role: AppRole,
  });

  const ProgressEntry = IDL.Record({
    byEmail: IDL.Text,
    date: IDL.Text,
    id: IDL.Nat,
    notes: IDL.Text,
    pct: IDL.Nat,
    photos: IDL.Vec(IDL.Text),
    projectId: IDL.Nat,
  });

  const PayrollRecord = IDL.Record({
    approvedBy: IDL.Text,
    id: IDL.Nat,
    period: IDL.Text,
    projectId: IDL.Nat,
    status: IDL.Text,
    submittedBy: IDL.Text,
    totalAmount: IDL.Nat,
  });

  const Notification = IDL.Record({
    content: IDL.Text,
    id: IDL.Nat,
    isRead: IDL.Bool,
    nType: IDL.Text,
    timestamp: IDL.Text,
    userEmail: IDL.Text,
  });

  const MaterialTx = IDL.Record({
    byEmail: IDL.Text,
    date: IDL.Text,
    id: IDL.Nat,
    materialId: IDL.Nat,
    notes: IDL.Text,
    projectId: IDL.Nat,
    qty: IDL.Nat,
    txType: IDL.Text,
  });

  const Material = IDL.Record({
    id: IDL.Nat,
    name: IDL.Text,
    priceUsd: IDL.Nat,
    projectId: IDL.Nat,
    reorderLevel: IDL.Nat,
    stock: IDL.Nat,
    supplier: IDL.Text,
    unit: IDL.Text,
  });

  const ChatMessage = IDL.Record({
    id: IDL.Nat,
    isDM: IDL.Bool,
    projectId: IDL.Nat,
    receiverEmail: IDL.Text,
    senderEmail: IDL.Text,
    senderName: IDL.Text,
    senderRole: IDL.Text,
    text: IDL.Text,
    timestamp: IDL.Text,
  });

  const AuditEntry = IDL.Record({
    action: IDL.Text,
    area: IDL.Text,
    details: IDL.Text,
    id: IDL.Nat,
    timestamp: IDL.Text,
    userEmail: IDL.Text,
  });

  const AttendanceRecord = IDL.Record({
    date: IDL.Text,
    projectId: IDL.Nat,
    status: IDL.Text,
    workerId: IDL.Nat,
  });

  const AddMaterialResult = IDL.Record({
    materialId: IDL.Nat,
    message: IDL.Text,
    ok: IDL.Bool,
  });
  const AddProgressResult = IDL.Record({
    entryId: IDL.Nat,
    message: IDL.Text,
    ok: IDL.Bool,
  });
  const AddWorkerResult = IDL.Record({
    message: IDL.Text,
    ok: IDL.Bool,
    workerId: IDL.Nat,
  });
  const OkMessage = IDL.Record({ message: IDL.Text, ok: IDL.Bool });
  const OkBool = IDL.Record({ ok: IDL.Bool });
  const CreateProjectResult = IDL.Record({
    message: IDL.Text,
    ok: IDL.Bool,
    projectId: IDL.Nat,
  });
  const JoinProjectResult = IDL.Record({
    message: IDL.Text,
    ok: IDL.Bool,
    projectId: IDL.Nat,
  });
  const LoginResult = IDL.Record({
    currency: IDL.Text,
    message: IDL.Text,
    name: IDL.Text,
    nationality: IDL.Text,
    ok: IDL.Bool,
    phone: IDL.Text,
    role: IDL.Text,
  });
  const PostChatResult = IDL.Record({ messageId: IDL.Nat, ok: IDL.Bool });
  const SubmitPayrollResult = IDL.Record({
    message: IDL.Text,
    ok: IDL.Bool,
    payrollId: IDL.Nat,
  });

  return IDL.Service({
    _initializeAccessControlWithSecret: IDL.Func([IDL.Text], [], []),
    addMaterial: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [AddMaterialResult],
      [],
    ),
    addProgress: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [AddProgressResult],
      [],
    ),
    addWorker: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AddWorkerResult],
      [],
    ),
    approvePayroll: IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [OkMessage], []),
    assignCallerUserRole: IDL.Func([IDL.Principal, UserRole], [], []),
    changePassword: IDL.Func([IDL.Text, IDL.Text, IDL.Text], [OkMessage], []),
    createProject: IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [CreateProjectResult],
      [],
    ),
    getAllProjects: IDL.Func([], [IDL.Vec(Project)], ['query']),
    getAttendance: IDL.Func([IDL.Nat], [IDL.Vec(AttendanceRecord)], ['query']),
    getAuditLog: IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
    getCallerUserRole: IDL.Func([], [UserRole], ['query']),
    getDMChat: IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    getGroupChat: IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    getMaterialTx: IDL.Func([IDL.Nat], [IDL.Vec(MaterialTx)], ['query']),
    getMaterials: IDL.Func([IDL.Nat], [IDL.Vec(Material)], ['query']),
    getNotifications: IDL.Func([IDL.Text], [IDL.Vec(Notification)], ['query']),
    getPayroll: IDL.Func([IDL.Nat], [IDL.Vec(PayrollRecord)], ['query']),
    getProgress: IDL.Func([IDL.Nat], [IDL.Vec(ProgressEntry)], ['query']),
    getProjectMembers: IDL.Func([IDL.Nat], [IDL.Vec(ProjectMember)], ['query']),
    getUserProjects: IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    getWorkers: IDL.Func([IDL.Nat], [IDL.Vec(Worker)], ['query']),
    isCallerAdmin: IDL.Func([], [IDL.Bool], ['query']),
    joinProject: IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AppRole],
      [JoinProjectResult],
      [],
    ),
    login: IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    markAllNotifsRead: IDL.Func([IDL.Text], [OkBool], []),
    markAttendance: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [OkMessage],
      [],
    ),
    markNotifRead: IDL.Func([IDL.Text, IDL.Nat], [OkBool], []),
    postChat: IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [PostChatResult],
      [],
    ),
    recordTx: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [OkMessage],
      [],
    ),
    register: IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, AppRole],
      [OkMessage],
      [],
    ),
    seedDemo: IDL.Func([], [OkBool], []),
    submitPayroll: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [SubmitPayrollResult],
      [],
    ),
    updateMaterial: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [OkMessage],
      [],
    ),
    updateProfile: IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [OkMessage],
      [],
    ),
    updateTeamCode: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [OkMessage],
      [],
    ),
    updateWorker: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [OkMessage],
      [],
    ),
    verifyProjectPassword: IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [OkMessage],
      [],
    ),
  });
};

export const init = ({ IDL }) => { return []; };
