/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  Actor,
  HttpAgent,
  type HttpAgentOptions,
  type ActorConfig,
  type Agent,
  type ActorSubclass,
} from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";

export type AppRole =
  | "chiefEngineer"
  | "siteEngineer"
  | "materialsEngineer"
  | "siteOwner";

export type UserRole = "admin" | "user" | "guest";

export interface CanisterWorker {
  dailyWage: bigint;
  dialCode: string;
  id: bigint;
  name: string;
  phone: string;
  projectId: bigint;
  skill: string;
  wEmail: string;
}

export interface CanisterProject {
  budget: bigint;
  completion: bigint;
  createdBy: string;
  id: bigint;
  location: string;
  name: string;
  pwHash: string;
  startDate: string;
  teamCode: string;
}

export interface CanisterProjectMember {
  email: string;
  projectId: bigint;
  role: AppRole;
}

export interface CanisterProgressEntry {
  byEmail: string;
  date: string;
  id: bigint;
  notes: string;
  pct: bigint;
  photos: Array<string>;
  projectId: bigint;
}

export interface CanisterPayrollRecord {
  approvedBy: string;
  id: bigint;
  period: string;
  projectId: bigint;
  status: string;
  submittedBy: string;
  totalAmount: bigint;
}

export interface CanisterNotification {
  content: string;
  id: bigint;
  isRead: boolean;
  nType: string;
  timestamp: string;
  userEmail: string;
}

export interface CanisterMaterialTx {
  byEmail: string;
  date: string;
  id: bigint;
  materialId: bigint;
  notes: string;
  projectId: bigint;
  qty: bigint;
  txType: string;
}

export interface CanisterMaterial {
  id: bigint;
  name: string;
  priceUsd: bigint;
  projectId: bigint;
  reorderLevel: bigint;
  stock: bigint;
  supplier: string;
  unit: string;
}

export interface CanisterChatMessage {
  id: bigint;
  isDM: boolean;
  projectId: bigint;
  receiverEmail: string;
  senderEmail: string;
  senderName: string;
  senderRole: string;
  text: string;
  timestamp: string;
}

export interface CanisterAuditEntry {
  action: string;
  area: string;
  details: string;
  id: bigint;
  timestamp: string;
  userEmail: string;
}

export interface CanisterAttendanceRecord {
  date: string;
  projectId: bigint;
  status: string;
  workerId: bigint;
}

export interface backendInterface {
  _initializeAccessControlWithSecret(secret: string): Promise<void>;
  addMaterial(
    email: string,
    projectId: bigint,
    name: string,
    unit: string,
    stock: bigint,
    reorderLevel: bigint,
    priceUsd: bigint,
    supplier: string,
    ts: string,
  ): Promise<{ materialId: bigint; message: string; ok: boolean }>;
  addProgress(
    email: string,
    projectId: bigint,
    pct: bigint,
    notes: string,
    date: string,
    photos: string[],
    ts: string,
  ): Promise<{ entryId: bigint; message: string; ok: boolean }>;
  addWorker(
    email: string,
    projectId: bigint,
    name: string,
    skill: string,
    dailyWage: bigint,
    phone: string,
    wEmail: string,
    dialCode: string,
    ts: string,
  ): Promise<{ message: string; ok: boolean; workerId: bigint }>;
  approvePayroll(
    email: string,
    projectId: bigint,
    payrollId: bigint,
    ts: string,
  ): Promise<{ message: string; ok: boolean }>;
  assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
  changePassword(
    email: string,
    oldPw: string,
    newPw: string,
  ): Promise<{ message: string; ok: boolean }>;
  createProject(
    creatorEmail: string,
    name: string,
    location: string,
    startDate: string,
    teamCode: string,
    teamPassword: string,
    budget: bigint,
    ts: string,
  ): Promise<{ message: string; ok: boolean; projectId: bigint }>;
  getAllProjects(): Promise<CanisterProject[]>;
  getAttendance(projectId: bigint): Promise<CanisterAttendanceRecord[]>;
  getAuditLog(email: string, projectId: bigint): Promise<CanisterAuditEntry[]>;
  getCallerUserRole(): Promise<UserRole>;
  getDMChat(
    projectId: bigint,
    email1: string,
    email2: string,
  ): Promise<CanisterChatMessage[]>;
  getGroupChat(projectId: bigint): Promise<CanisterChatMessage[]>;
  getMaterialTx(projectId: bigint): Promise<CanisterMaterialTx[]>;
  getMaterials(projectId: bigint): Promise<CanisterMaterial[]>;
  getNotifications(email: string): Promise<CanisterNotification[]>;
  getPayroll(projectId: bigint): Promise<CanisterPayrollRecord[]>;
  getProgress(projectId: bigint): Promise<CanisterProgressEntry[]>;
  getProjectMembers(projectId: bigint): Promise<CanisterProjectMember[]>;
  getUserProjects(email: string): Promise<CanisterProject[]>;
  getWorkers(projectId: bigint): Promise<CanisterWorker[]>;
  isCallerAdmin(): Promise<boolean>;
  joinProject(
    email: string,
    teamCode: string,
    teamPassword: string,
    role: { [K in AppRole]?: null },
  ): Promise<{ message: string; ok: boolean; projectId: bigint }>;
  login(
    email: string,
    password: string,
  ): Promise<{
    currency: string;
    message: string;
    name: string;
    nationality: string;
    ok: boolean;
    phone: string;
    role: string;
  }>;
  markAllNotifsRead(email: string): Promise<{ ok: boolean }>;
  markAttendance(
    email: string,
    projectId: bigint,
    workerId: bigint,
    date: string,
    status: string,
  ): Promise<{ message: string; ok: boolean }>;
  markNotifRead(email: string, notifId: bigint): Promise<{ ok: boolean }>;
  postChat(
    projectId: bigint,
    senderEmail: string,
    senderName: string,
    senderRole: string,
    text: string,
    timestamp: string,
    isDM: boolean,
    receiverEmail: string,
  ): Promise<{ messageId: bigint; ok: boolean }>;
  recordTx(
    email: string,
    projectId: bigint,
    materialId: bigint,
    txType: string,
    qty: bigint,
    date: string,
    notes: string,
    ts: string,
  ): Promise<{ message: string; ok: boolean }>;
  register(
    email: string,
    name: string,
    password: string,
    nationality: string,
    currency: string,
    phone: string,
    role: { [K in AppRole]?: null },
  ): Promise<{ message: string; ok: boolean }>;
  seedDemo(): Promise<{ ok: boolean }>;
  submitPayroll(
    email: string,
    projectId: bigint,
    period: string,
    totalAmount: bigint,
    ts: string,
  ): Promise<{ message: string; ok: boolean; payrollId: bigint }>;
  updateMaterial(
    email: string,
    projectId: bigint,
    materialId: bigint,
    name: string,
    unit: string,
    stock: bigint,
    reorderLevel: bigint,
    priceUsd: bigint,
    supplier: string,
  ): Promise<{ message: string; ok: boolean }>;
  updateProfile(
    email: string,
    password: string,
    name: string,
    nationality: string,
    currency: string,
    phone: string,
  ): Promise<{ message: string; ok: boolean }>;
  updateTeamCode(
    email: string,
    projectId: bigint,
    newCode: string,
    newPassword: string,
  ): Promise<{ message: string; ok: boolean }>;
  updateWorker(
    email: string,
    projectId: bigint,
    workerId: bigint,
    name: string,
    skill: string,
    dailyWage: bigint,
    phone: string,
    wEmail: string,
    dialCode: string,
  ): Promise<{ message: string; ok: boolean }>;
  verifyProjectPassword(
    email: string,
    projectId: bigint,
    teamPassword: string,
  ): Promise<{ message: string; ok: boolean }>;
}

// Helper: convert AppRole string to Candid variant
function toAppRoleVariant(role: AppRole): { [K in AppRole]?: null } {
  return { [role]: null };
}

// Helper: convert Candid AppRole variant to string
function fromAppRoleVariant(variant: Record<string, null>): AppRole {
  return Object.keys(variant)[0] as AppRole;
}

export interface CreateActorOptions {
  agent?: Agent;
  agentOptions?: HttpAgentOptions;
  actorOptions?: ActorConfig;
  processError?: (error: unknown) => never;
}

export class ExternalBlob {
  _blob?: Uint8Array<ArrayBuffer> | null;
  directURL: string;
  onProgress?: (percentage: number) => void = undefined;

  private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null) {
    if (blob) {
      this._blob = blob;
    }
    this.directURL = directURL;
  }

  static fromURL(url: string): ExternalBlob {
    return new ExternalBlob(url, null);
  }

  static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
    const url = URL.createObjectURL(
      new Blob([new Uint8Array(blob)], { type: "application/octet-stream" }),
    );
    return new ExternalBlob(url, blob);
  }

  public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
    if (this._blob) {
      return this._blob;
    }
    const response = await fetch(this.directURL);
    const blob = await response.blob();
    this._blob = new Uint8Array(await blob.arrayBuffer());
    return this._blob;
  }

  public getDirectURL(): string {
    return this.directURL;
  }

  public withUploadProgress(
    onProgress: (percentage: number) => void,
  ): ExternalBlob {
    this.onProgress = onProgress;
    return this;
  }
}

export class Backend implements backendInterface {
  constructor(
    private actor: ActorSubclass<_SERVICE>,
    private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
    private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
    private processError?: (error: unknown) => never,
  ) {}

  private async call<T>(fn: () => Promise<T>): Promise<T> {
    if (this.processError) {
      try {
        return await fn();
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    }
    return fn();
  }

  async _initializeAccessControlWithSecret(secret: string): Promise<void> {
    return this.call(() => this.actor._initializeAccessControlWithSecret(secret));
  }

  async addMaterial(
    email: string,
    projectId: bigint,
    name: string,
    unit: string,
    stock: bigint,
    reorderLevel: bigint,
    priceUsd: bigint,
    supplier: string,
    ts: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.addMaterial(
        email, projectId, name, unit, stock, reorderLevel, priceUsd, supplier, ts,
      );
      return result[0] ?? result;
    });
  }

  async addProgress(
    email: string,
    projectId: bigint,
    pct: bigint,
    notes: string,
    date: string,
    photos: string[],
    ts: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.addProgress(
        email, projectId, pct, notes, date, photos, ts,
      );
      return result[0] ?? result;
    });
  }

  async addWorker(
    email: string,
    projectId: bigint,
    name: string,
    skill: string,
    dailyWage: bigint,
    phone: string,
    wEmail: string,
    dialCode: string,
    ts: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.addWorker(
        email, projectId, name, skill, dailyWage, phone, wEmail, dialCode, ts,
      );
      return result[0] ?? result;
    });
  }

  async approvePayroll(email: string, projectId: bigint, payrollId: bigint, ts: string) {
    return this.call(async () => {
      const result = await this.actor.approvePayroll(email, projectId, payrollId, ts);
      return result[0] ?? result;
    });
  }

  async assignCallerUserRole(user: Principal, role: UserRole): Promise<void> {
    const variant = { [role]: null } as any;
    return this.call(() => this.actor.assignCallerUserRole(user, variant));
  }

  async changePassword(email: string, oldPw: string, newPw: string) {
    return this.call(async () => {
      const result = await this.actor.changePassword(email, oldPw, newPw);
      return result[0] ?? result;
    });
  }

  async createProject(
    creatorEmail: string,
    name: string,
    location: string,
    startDate: string,
    teamCode: string,
    teamPassword: string,
    budget: bigint,
    ts: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.createProject(
        creatorEmail, name, location, startDate, teamCode, teamPassword, budget, ts,
      );
      return result[0] ?? result;
    });
  }

  async getAllProjects() {
    return this.call(() => this.actor.getAllProjects());
  }

  async getAttendance(projectId: bigint) {
    return this.call(() => this.actor.getAttendance(projectId));
  }

  async getAuditLog(email: string, projectId: bigint) {
    return this.call(() => this.actor.getAuditLog(email, projectId));
  }

  async getCallerUserRole(): Promise<UserRole> {
    return this.call(async () => {
      const result = await this.actor.getCallerUserRole();
      return Object.keys(result)[0] as UserRole;
    });
  }

  async getDMChat(projectId: bigint, email1: string, email2: string) {
    return this.call(() => this.actor.getDMChat(projectId, email1, email2));
  }

  async getGroupChat(projectId: bigint) {
    return this.call(() => this.actor.getGroupChat(projectId));
  }

  async getMaterialTx(projectId: bigint) {
    return this.call(() => this.actor.getMaterialTx(projectId));
  }

  async getMaterials(projectId: bigint) {
    return this.call(() => this.actor.getMaterials(projectId));
  }

  async getNotifications(email: string) {
    return this.call(() => this.actor.getNotifications(email));
  }

  async getPayroll(projectId: bigint) {
    return this.call(() => this.actor.getPayroll(projectId));
  }

  async getProgress(projectId: bigint) {
    return this.call(() => this.actor.getProgress(projectId));
  }

  async getProjectMembers(projectId: bigint) {
    return this.call(async () => {
      const result = await this.actor.getProjectMembers(projectId);
      return result.map((m) => ({
        ...m,
        role: fromAppRoleVariant(m.role as any) as AppRole,
      }));
    });
  }

  async getUserProjects(email: string) {
    return this.call(() => this.actor.getUserProjects(email));
  }

  async getWorkers(projectId: bigint) {
    return this.call(() => this.actor.getWorkers(projectId));
  }

  async isCallerAdmin(): Promise<boolean> {
    return this.call(() => this.actor.isCallerAdmin());
  }

  async joinProject(
    email: string,
    teamCode: string,
    teamPassword: string,
    role: { [K in AppRole]?: null },
  ) {
    return this.call(async () => {
      const result = await this.actor.joinProject(
        email, teamCode, teamPassword, role as any,
      );
      return result[0] ?? result;
    });
  }

  async login(email: string, password: string) {
    return this.call(async () => {
      const result = await this.actor.login(email, password);
      return result[0] ?? result;
    });
  }

  async markAllNotifsRead(email: string) {
    return this.call(async () => {
      const result = await this.actor.markAllNotifsRead(email);
      return result[0] ?? result;
    });
  }

  async markAttendance(
    email: string,
    projectId: bigint,
    workerId: bigint,
    date: string,
    status: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.markAttendance(
        email, projectId, workerId, date, status,
      );
      return result[0] ?? result;
    });
  }

  async markNotifRead(email: string, notifId: bigint) {
    return this.call(async () => {
      const result = await this.actor.markNotifRead(email, notifId);
      return result[0] ?? result;
    });
  }

  async postChat(
    projectId: bigint,
    senderEmail: string,
    senderName: string,
    senderRole: string,
    text: string,
    timestamp: string,
    isDM: boolean,
    receiverEmail: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.postChat(
        projectId, senderEmail, senderName, senderRole, text, timestamp, isDM, receiverEmail,
      );
      return result[0] ?? result;
    });
  }

  async recordTx(
    email: string,
    projectId: bigint,
    materialId: bigint,
    txType: string,
    qty: bigint,
    date: string,
    notes: string,
    ts: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.recordTx(
        email, projectId, materialId, txType, qty, date, notes, ts,
      );
      return result[0] ?? result;
    });
  }

  async register(
    email: string,
    name: string,
    password: string,
    nationality: string,
    currency: string,
    phone: string,
    role: { [K in AppRole]?: null },
  ) {
    return this.call(async () => {
      const result = await this.actor.register(
        email, name, password, nationality, currency, phone, role as any,
      );
      return result[0] ?? result;
    });
  }

  async seedDemo() {
    return this.call(async () => {
      const result = await this.actor.seedDemo();
      return result[0] ?? result;
    });
  }

  async submitPayroll(
    email: string,
    projectId: bigint,
    period: string,
    totalAmount: bigint,
    ts: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.submitPayroll(
        email, projectId, period, totalAmount, ts,
      );
      return result[0] ?? result;
    });
  }

  async updateMaterial(
    email: string,
    projectId: bigint,
    materialId: bigint,
    name: string,
    unit: string,
    stock: bigint,
    reorderLevel: bigint,
    priceUsd: bigint,
    supplier: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.updateMaterial(
        email, projectId, materialId, name, unit, stock, reorderLevel, priceUsd, supplier,
      );
      return result[0] ?? result;
    });
  }

  async updateProfile(
    email: string,
    password: string,
    name: string,
    nationality: string,
    currency: string,
    phone: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.updateProfile(
        email, password, name, nationality, currency, phone,
      );
      return result[0] ?? result;
    });
  }

  async updateTeamCode(
    email: string,
    projectId: bigint,
    newCode: string,
    newPassword: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.updateTeamCode(
        email, projectId, newCode, newPassword,
      );
      return result[0] ?? result;
    });
  }

  async updateWorker(
    email: string,
    projectId: bigint,
    workerId: bigint,
    name: string,
    skill: string,
    dailyWage: bigint,
    phone: string,
    wEmail: string,
    dialCode: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.updateWorker(
        email, projectId, workerId, name, skill, dailyWage, phone, wEmail, dialCode,
      );
      return result[0] ?? result;
    });
  }

  async verifyProjectPassword(
    email: string,
    projectId: bigint,
    teamPassword: string,
  ) {
    return this.call(async () => {
      const result = await this.actor.verifyProjectPassword(
        email, projectId, teamPassword,
      );
      return result[0] ?? result;
    });
  }
}

export function createActor(
  canisterId: string,
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  options: CreateActorOptions = {},
): Backend {
  const agent =
    options.agent ||
    HttpAgent.createSync({
      ...options.agentOptions,
    });
  if (options.agent && options.agentOptions) {
    console.warn(
      "Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.",
    );
  }
  const actor = Actor.createActor<_SERVICE>(idlFactory, {
    agent,
    canisterId: canisterId,
    ...options.actorOptions,
  });
  return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
